# Generated by Django 4.2.6 on 2024-07-10 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listing_watchlist_related_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
